backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "poems"
    label: "Өлеңдер"
    folder: "content/poems"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Атауы", name: "title", widget: "string"}
      - {label: "Жылы", name: "year", widget: "number"}
      - {label: "Мәтін", name: "body", widget: "markdown"}
